#!/usr/bin/env bash
source ./lib/libfloat

ORIG2="$3"
if [ -z "$ORIG2" ]; then
  ORIG2="789.012"
fi
ORIG1="$2"
if [ -z "$ORIG1" ]; then
  ORIG1="123.456"
fi
OP="$1"
if [ -z "$OP" ]; then
  OP="-a"
fi

if [ $OP == -a ]; then
  echo " "
  echo "Adding floats $ORIG1 and $ORIG2"
  add $ORIG1 $ORIG2
  echo " "
  echo "Result is $RETURN"
  echo " "
fi
if [ $OP == -s ]; then
  echo " "
  echo "Subtracting floats $ORIG1 and $ORIG2"
  sub $ORIG1 $ORIG2
  echo " "
  echo "Result is $RETURN"
  echo " "
fi
if [ $OP == -m ]; then
  echo " "
  echo "Multiplying floats $ORIG1 and $ORIG2"
  mul $ORIG1 $ORIG2
  echo " "
  echo "Result is $RETURN"
  echo " "
fi
if [ $OP == -d ]; then
  echo " "
  echo "Dividing floats $ORIG1 and $ORIG2"
  div $ORIG1 $ORIG2
  echo " "
  echo "Result is $RETURN"
  echo " "
fi

if [ $OP == -gth ]; then
  echo " "
  if gth $ORIG1 $ORIG2; then
    echo "$ORIG1 is greater than $ORIG2"
  else
    echo "$ORIG1 is not greater than $ORIG2"
  fi
  echo " "
fi

if [ $OP == -lth ]; then
  echo " "
  if lth $ORIG1 $ORIG2; then
    echo "$ORIG1 is less than $ORIG2"
  else
    echo "$ORIG1 is not less than $ORIG2"
  fi
  echo " "
fi

if [ $OP == -eql ]; then
  echo " "
  if eql $ORIG1 $ORIG2; then
    echo "$ORIG1 is equal to $ORIG2"
  else
    echo "$ORIG1 is not equal to $ORIG2"
  fi
  echo " "
fi

if [ $OP == -geq ]; then
  echo " "
  if geq $ORIG1 $ORIG2; then
    echo "$ORIG1 is greater than or equal to $ORIG2"
  else
    echo "$ORIG1 is not greater than or equal to $ORIG2"
  fi
  echo " "
fi

if [ $OP == -leq ]; then
  echo " "
  if leq $ORIG1 $ORIG2; then
    echo "$ORIG1 is less than or equal to $ORIG2"
  else
    echo "$ORIG1 is not less than or equal to $ORIG2"
  fi
  echo " "
fi
